language: python
python:
  - '2.7'
before_install:
  - bin/get-protoc
  - bin/get-phantomjs
install:
  - npm install
  - pip install -e .
  - pip install pilgrim3[test]
script: bin/test
env:
  - PROTOC_EXE=${TRAVIS_BUILD_DIR}/protoc/bin/protoc PATH=${TRAVIS_BUILD_DIR}/travis-phantomjs/phantomjs-2.1.1-linux-x86_64/bin:$PATH
notifications:
  slack:
    secure: OmGJKFuoQM/BHwIG85KiUOk/eAEfu4TcBiSZ9GEcVM9L5znMbml0jkUzpcHUSXkrPg6+gQOBOne6xy7Mix+0iOt4UeHDr4OQzyNGHsH6uzUwGSvdHZi6sXMU50YOgezIJ/2bJGoJfmVbW2pv/oHLBSnA23L1bTNwVeogLfWr1ny1M6NbDbPLaVw0vnYJfgWe2Xh9McvZBaXWFF2p7VvPHYywsRTRGSZl/UqplZGLEQp9gM/DEC5V3M2wIea399ttTwALqlhN7pmN0QlGUb45Dc9bTg1FAbcid1RvIc2XcH1RAotADS8JAt26XAJ6d7P0kYQa+xl8F45oMCkskKsxF2lQlJfL/yFEHJ+LfaBn8DZbX4o2mfHrZ4kNOqdSqBhHUkMi8cvKck8PdNCzEP8QD5I+cB+mjKAySY0Bz6rh8PyV6F08d3y4RAtzG2TMoTYH8slK7NLRzZknxAgySYe7tv5AcvSTsnspLoZlnM0ELGAEUfbPJxVmIg2sR2bf2slNV7Q1Lv6ERrgsUaCa9OukUXqY/nlczz4gJA4q+P1sD7Te5gGI5I3nMYOazGhthLlIKHqUtBL22lGtROetSBvfoyrpGrylSR42vzY4rnuh4fU4OYAfTQxpUCAgwzaJIT17dH8MMnIzap1GQNRxfk/QeHpcWXI2Eb8z3cNEtvZSNxU=
cache:
  pip: true
  directories:
    - node_modules
before_cache:
  - rm -rf ${HOME}/.cache/pip/log/debug.log
  - rm -rf ${HOME}/.cache/pip/http
