language: python
python:
  - "2.7"
before_install:
  - bin/get-protoc
install:
  - npm install
  - pip install -e .
  - pip install pilgrim3[test]
  - test/support/proto3/compile
script: bin/test
env:
  - PROTOC_EXE=${TRAVIS_BUILD_DIR}/protoc/bin/protoc
